# Generated by Django 5.2.1 on 2025-05-10 05:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_user_detailes_delete_kkk'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_detailes',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='user_detailes',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
